options {
  directory "/var/cache/bind";
  recursion no;
  allow-query { any; };
  dnssec-validation no;
  listen-on { any; };
  listen-on-v6 { any; };
};

zone "test." {
  type slave;
  masters { 10.33.0.74; };
  file "/var/cache/bind/db.test";
};
