options {
    directory "/var/cache/bind";
    listen-on { none; };
    listen-on-v6 { any; };
    recursion no;
    allow-query { any; };
};

zone "services.test" {
    type master;
    file "/etc/bind/db.services.test";
};
