options {
    directory "/var/cache/bind";
    listen-on { none; };
    listen-on-v6 { any; };
    recursion no;
};

zone "test" {
    type master;
    file "/etc/bind/db.test";
    allow-transfer { 2001:db8:1200:4::10; };
    notify yes;
    also-notify { 2001:db8:1200:4::10; };
};
