options {
    directory "/var/cache/bind";
    listen-on { none; };
    listen-on-v6 { any; };
    recursion yes;
    allow-recursion { any; };
    dnssec-validation no;
    empty-zones-enable no;
};

zone "." {
    type hint;
    file "/etc/bind/db.root.hints";
};
