options {
    directory "/var/cache/bind";
    listen-on { 10.33.0.202; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
};

zone "services.test" {
    type master;
    file "/etc/bind/db.services.test";
};
