options {
  directory "/var/cache/bind";
  recursion no;
  allow-query { any; };
  allow-transfer { none; };
  dnssec-validation no;
  listen-on { any; };
  listen-on-v6 { any; };
};

zone "services.test." {
  type master;
  file "/etc/bind/db.services.test";
};
