options {
    directory "/var/cache/bind";
    listen-on { none; };
    listen-on-v6 { any; };
    recursion no;
    dnssec-validation no;
    empty-zones-enable no;
};

zone "." {
    type master;
    file "/etc/bind/db.root";
};
