options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
    dnssec-validation no;
};

zone "." {
    type master;
    file "/etc/bind/db.root";
};
