options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { any; };
    allow-query { any; };
    recursion no;
    dnssec-validation no;
};

zone "test" {
    type slave;
    file "/var/cache/bind/db.test";
    masters { 2001:db8:1100:1::10; };
};
