options {
        directory "/var/cache/bind";
        listen-on { 100.0.6.2; };
        listen-on-v6 { none; };
        allow-query { any; };
        recursion no;
        dnssec-validation no;
};

zone "." {
        type master;
        file "/etc/bind/db.root";
};
