options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
    dnssec-validation no;
};

zone "test" {
    type slave;
    file "/var/cache/bind/db.test";
    masters { 10.33.0.74; };
};
