options {
    directory "/var/cache/bind";
    listen-on { none; };
    listen-on-v6 { 2001:db8:1200:4::10; };
    recursion no;
    allow-query { any; };
    dnssec-validation no;
};

zone "test." {
    type slave;
    file "/var/cache/bind/db.test";
    masters { 2001:db8:1200:1::10; };
};
