options {
    directory "/var/cache/bind";
    listen-on { none; };
    listen-on-v6 { any; };
    recursion no;
    allow-query { any; };
};

zone "." {
    type primary;
    file "/etc/bind/db.root.internal";
    allow-transfer { none; };
};
