options {
  directory "/var/cache/bind";
  recursion no;
  allow-query { any; };
  allow-transfer { 2001:db8:1200:4::10; };
  dnssec-validation no;
  listen-on { any; };
  listen-on-v6 { any; };
};
zone "test." { type master; file "/etc/bind/db.test"; };
