options {
    directory "/var/cache/bind";
    listen-on { 10.33.0.10; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
};

zone "." {
    type master;
    file "/etc/bind/db.root";
};
