options {
        directory "/var/cache/bind";
        listen-on { any; };
        listen-on-v6 { any; };
        allow-query { any; };
        recursion no;
        dnssec-validation no;
};

zone "test." {
        type master;
        file "/etc/bind/db.test";
};
