options {
    directory "/var/cache/bind";
    listen-on { 10.33.1.10; };
    listen-on-v6 { none; };
    recursion yes;
    allow-query { any; };
    allow-recursion { any; };
    dnssec-validation no;
};

zone "." IN {
    type hint;
    file "/etc/bind/db.root-hint";
};
