options {
    directory "/var/cache/bind";
    listen-on { none; };
    listen-on-v6 { any; };
    recursion no;
    dnssec-validation no;
    empty-zones-enable no;
};

zone "test" {
    type slave;
    masters { 2001:db8:1100:1::10; };
    file "/var/cache/bind/db.test";
};
