options {
    directory "/var/cache/bind";
    listen-on { any; };
    listen-on-v6 { any; };
    recursion yes;
    allow-query { any; };
    dnssec-validation no;
};

zone "." {
    type hint;
    file "/etc/bind/root.hints";
};
