options {
        directory "/var/cache/bind";
        listen-on { none; };
        listen-on-v6 { any; };
        recursion no;
        allow-query { any; };
        dnssec-validation no;
};

zone "test." {
        type master;
        file "/etc/bind/db.test";
        allow-transfer { 2001:db8:1100:2::10; };
        also-notify { 2001:db8:1100:2::10; };
        notify yes;
};
