options {
    directory "/var/cache/bind";
    listen-on { 10.33.0.74; };
    listen-on-v6 { none; };
    recursion no;
    allow-query { any; };
    dnssec-validation no;
};

zone "test." IN {
    type master;
    file "/etc/bind/db.test";
    allow-transfer { 10.33.0.138; };
    notify yes;
};
