options {
        directory "/var/cache/bind";
        listen-on { 100.0.0.2; };
        listen-on-v6 { 2001:8::2; };
        allow-query { any; };
        recursion yes;
        dnssec-validation no;
};

zone "." {
        type hint;
        file "/etc/bind/db.root-hint";
};
