options {
  directory "/var/cache/bind";
  recursion no;
  allow-query { any; };
  allow-transfer { 10.33.0.138; };
  dnssec-validation no;
  listen-on { any; };
  listen-on-v6 { any; };
};

zone "test." {
  type master;
  file "/etc/bind/db.test";
};
