options {
    directory "/var/cache/bind";
    listen-on { 10.33.1.10; };
    listen-on-v6 { none; };
    recursion yes;
    allow-recursion { any; };
    allow-query { any; };
};

zone "." {
    type hint;
    file "/etc/bind/db.root.hints";
};
