options {
        directory "/var/cache/bind";
        listen-on { any; };
        listen-on-v6 { any; };
        allow-query { any; };
        allow-recursion { any; };
        recursion yes;
        dnssec-validation no;
};

zone "." {
        type hint;
        file "/etc/bind/db.internal-root-hints";
};
